# 所有环境的通用配置，放在这里
spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
mapper:
  mappers: com.alan.api.core.mapper.MyMapper
  not-empty: false
  identity: MYSQL
mybatis:
  type-aliases-package: com.alan.api.model
  mapper-locations: classpath:mapper/**/*.xml