server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alan_dev?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.alan.api: debug
jwt:
  expiration-time: 24000
  header: Authorization
  token-prefix: Bearer
  privateKey: rsa/private-key.pem
  publicKey: rsa/public-key.pem
  authorities-key: auth




