# 开发环境配置
# 入口端口号
server:
  port: 8080

##################################
# spring 相关配置
##################################
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alan_dev?useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
logging:
  level:
    com.alan.api: debug





################################
# 日志级别
################################