spring:
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  resources:
    add-mappings: false   # 不映射工程中的静态文件
mapper:
  mappers: com.alan.api.core.mapper.MyMapper
  not-empty: false
  identity: MYSQL
mybatis:
  type-aliases-package: com.alan.api.model
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  page-size-zero: true
  helperDialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql